// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuItUnion.FeedbackBot.Data;

#nullable disable

namespace RuItUnion.FeedbackBot.Data.Migrations
{
    [DbContext(typeof(FeedbackBotContext))]
    partial class FeedbackBotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("RuItUnion.FeedbackBot.Data.Models.DbReply", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("ChatThreadId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("RuItUnion.FeedbackBot.Data.Models.DbTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserChatId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId")
                        .IsUnique();

                    b.HasIndex("UserChatId")
                        .IsUnique();

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("TgBotFrame.Commands.Authorization.Models.DbBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Until")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasDefaultValue(0u)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Until");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("TgBotFrame.Commands.Authorization.Models.DbRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MentionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasDefaultValue(0u)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = -50,
                            MentionEnabled = false,
                            Name = "service_admin",
                            Version = 0u
                        },
                        new
                        {
                            Id = -1,
                            MentionEnabled = false,
                            Name = "admin",
                            Version = 0u
                        },
                        new
                        {
                            Id = -2,
                            MentionEnabled = false,
                            Name = "ban_list",
                            Version = 0u
                        });
                });

            modelBuilder.Entity("TgBotFrame.Commands.Authorization.Models.DbRoleMember", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasDefaultValue(0u)
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleMembers");
                });

            modelBuilder.Entity("TgBotFrame.Commands.Authorization.Models.DbUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasDefaultValue(0u)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RuItUnion.FeedbackBot.Data.Models.DbReply", b =>
                {
                    b.HasOne("RuItUnion.FeedbackBot.Data.Models.DbTopic", "Topic")
                        .WithMany("Replies")
                        .HasForeignKey("ChatThreadId")
                        .HasPrincipalKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("RuItUnion.FeedbackBot.Data.Models.DbTopic", b =>
                {
                    b.HasOne("TgBotFrame.Commands.Authorization.Models.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgBotFrame.Commands.Authorization.Models.DbBan", b =>
                {
                    b.HasOne("TgBotFrame.Commands.Authorization.Models.DbUser", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TgBotFrame.Commands.Authorization.Models.DbRoleMember", b =>
                {
                    b.HasOne("TgBotFrame.Commands.Authorization.Models.DbRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgBotFrame.Commands.Authorization.Models.DbUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RuItUnion.FeedbackBot.Data.Models.DbTopic", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TgBotFrame.Commands.Authorization.Models.DbUser", b =>
                {
                    b.Navigation("Bans");
                });
#pragma warning restore 612, 618
        }
    }
}
